"""initial_schema

Revision ID: 387906f2c73e
Revises: 
Create Date: 2026-05-15 20:30:21.464324

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '387906f2c73e'
down_revision: Union[str, None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('users',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('username', sa.String(length=100), nullable=False),
    sa.Column('email', sa.String(length=255), nullable=True),
    sa.Column('phone', sa.String(length=20), nullable=True),
    sa.Column('hashed_password', sa.Text(), nullable=False),
    sa.Column('role', sa.String(length=20), nullable=True),
    sa.Column('turma', sa.String(length=20), nullable=True),
    sa.Column('plan', sa.String(length=20), nullable=True),
    sa.Column('style', sa.String(length=20), nullable=True),
    sa.Column('method', sa.String(length=20), nullable=True),
    sa.Column('contract_start', sa.Date(), nullable=True),
    sa.Column('contract_end', sa.Date(), nullable=True),
    sa.Column('credits_total', sa.Integer(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_users_id'), 'users', ['id'], unique=False)
    op.create_index(op.f('ix_users_username'), 'users', ['username'], unique=True)
    op.create_table('blocked_slots',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('date', sa.Date(), nullable=False),
    sa.Column('time_slot', sa.String(length=5), nullable=False),
    sa.Column('reason', sa.Text(), nullable=True),
    sa.Column('created_by', sa.Integer(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=True),
    sa.ForeignKeyConstraint(['created_by'], ['users.id'], ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('date', 'time_slot', name='uq_blocked_slot')
    )
    op.create_index(op.f('ix_blocked_slots_id'), 'blocked_slots', ['id'], unique=False)
    op.create_table('bookings',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('date', sa.Date(), nullable=False),
    sa.Column('time_slot', sa.String(length=5), nullable=False),
    sa.Column('status', sa.String(length=20), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=True),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('date', 'time_slot', name='uq_booking_slot')
    )
    op.create_index(op.f('ix_bookings_id'), 'bookings', ['id'], unique=False)
    op.create_table('quiz_responses',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=255), nullable=False),
    sa.Column('email', sa.String(length=255), nullable=True),
    sa.Column('phone', sa.String(length=20), nullable=True),
    sa.Column('turma', sa.String(length=20), nullable=True),
    sa.Column('level', sa.String(length=20), nullable=True),
    sa.Column('style', sa.String(length=20), nullable=True),
    sa.Column('method', sa.String(length=20), nullable=True),
    sa.Column('commitment', sa.String(length=20), nullable=True),
    sa.Column('topics', sa.ARRAY(sa.String()), nullable=True),
    sa.Column('user_id', sa.Integer(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=True),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_quiz_responses_id'), 'quiz_responses', ['id'], unique=False)
    op.drop_table('noma_alunos')
    op.drop_table('noma_quiz')
    op.drop_table('noma_agendamentos')
    op.drop_table('noma_liberados')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('noma_liberados',
    sa.Column('id', sa.INTEGER(), autoincrement=True, nullable=False),
    sa.Column('chave', sa.TEXT(), autoincrement=False, nullable=False),
    sa.Column('created_at', postgresql.TIMESTAMP(timezone=True), server_default=sa.text('now()'), autoincrement=False, nullable=True),
    sa.PrimaryKeyConstraint('id', name='noma_liberados_pkey'),
    sa.UniqueConstraint('chave', name='noma_liberados_chave_key')
    )
    op.create_table('noma_agendamentos',
    sa.Column('id', sa.INTEGER(), autoincrement=True, nullable=False),
    sa.Column('usuario', sa.TEXT(), autoincrement=False, nullable=False),
    sa.Column('data', sa.DATE(), autoincrement=False, nullable=False),
    sa.Column('horario', sa.TEXT(), autoincrement=False, nullable=False),
    sa.Column('created_at', postgresql.TIMESTAMP(timezone=True), server_default=sa.text('now()'), autoincrement=False, nullable=True),
    sa.PrimaryKeyConstraint('id', name='noma_agendamentos_pkey')
    )
    op.create_table('noma_quiz',
    sa.Column('id', sa.INTEGER(), autoincrement=True, nullable=False),
    sa.Column('nome', sa.TEXT(), autoincrement=False, nullable=True),
    sa.Column('email', sa.TEXT(), autoincrement=False, nullable=True),
    sa.Column('turma', sa.TEXT(), autoincrement=False, nullable=True),
    sa.Column('estilo', sa.TEXT(), autoincrement=False, nullable=True),
    sa.Column('metodo', sa.TEXT(), autoincrement=False, nullable=True),
    sa.Column('compromisso', sa.TEXT(), autoincrement=False, nullable=True),
    sa.Column('temas', sa.TEXT(), autoincrement=False, nullable=True),
    sa.Column('created_at', postgresql.TIMESTAMP(timezone=True), server_default=sa.text('now()'), autoincrement=False, nullable=True),
    sa.PrimaryKeyConstraint('id', name='noma_quiz_pkey')
    )
    op.create_table('noma_alunos',
    sa.Column('id', sa.INTEGER(), autoincrement=True, nullable=False),
    sa.Column('usuario', sa.TEXT(), autoincrement=False, nullable=False),
    sa.Column('senha_hash', sa.TEXT(), autoincrement=False, nullable=False),
    sa.Column('plano', sa.TEXT(), server_default=sa.text("'light'::text"), autoincrement=False, nullable=False),
    sa.Column('data_inicio', sa.DATE(), autoincrement=False, nullable=True),
    sa.Column('data_fim', sa.DATE(), autoincrement=False, nullable=True),
    sa.Column('created_at', postgresql.TIMESTAMP(timezone=True), server_default=sa.text('now()'), autoincrement=False, nullable=True),
    sa.PrimaryKeyConstraint('id', name='noma_alunos_pkey'),
    sa.UniqueConstraint('usuario', name='noma_alunos_usuario_key')
    )
    op.drop_index(op.f('ix_quiz_responses_id'), table_name='quiz_responses')
    op.drop_table('quiz_responses')
    op.drop_index(op.f('ix_bookings_id'), table_name='bookings')
    op.drop_table('bookings')
    op.drop_index(op.f('ix_blocked_slots_id'), table_name='blocked_slots')
    op.drop_table('blocked_slots')
    op.drop_index(op.f('ix_users_username'), table_name='users')
    op.drop_index(op.f('ix_users_id'), table_name='users')
    op.drop_table('users')
    # ### end Alembic commands ###
